/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_JuegoTerminado;
import javax.swing.table.DefaultTableModel;
import modelo.MetodosJugador;

/**
 *
 * @author Carlos
 */
public class FRM_JuegoTerminado extends javax.swing.JFrame {

    Controlador_FRM_JuegoTerminado controlador_FRM_JuegoTerminado;
    MetodosJugador metodosJugador;
    DefaultTableModel modelo;
    
    public FRM_JuegoTerminado() {
        initComponents();
        setLocationRelativeTo(this);
        modelo= new DefaultTableModel();
        controlador_FRM_JuegoTerminado= new Controlador_FRM_JuegoTerminado(this);
        metodosJugador= new MetodosJugador(this);
        colocarTitulos();
        metodosJugador.cargarTabla();
        agregarEventos();
    }
    
    public void colocarTitulos() {
        this.jtab_Puntuaciones.setModel(modelo);
        modelo.addColumn("Name");
        modelo.addColumn("Time");
    }
    public void agregarEventos() {
        this.btn_Guardar.addActionListener(controlador_FRM_JuegoTerminado);
    }
    public void agregarInformacion() {
        String arreglo[]= new String [2];
        arreglo[0]=this.jt_Nombre.getText();
        arreglo[1]=this.jt_Tiempo.getText();
        metodosJugador.agregarJugador(arreglo);
        metodosJugador.escribirInformacionEnElArchivo();
        metodosJugador.actualizarArray();
        modelo.addRow(arreglo);
    }
    public void agregarInformacionTabla(String arreglo[]) {
        modelo.addRow(arreglo);
    }
    public void colocarTiempo(String tiempo) {
        this.jt_Tiempo.setText(tiempo);
    }
    public void habililitar() {
        this.jt_Nombre.setEnabled(true);
        this.btn_Guardar.setEnabled(true);
    }
    public void deshabililitar() {
        this.jt_Nombre.setEnabled(false);
        this.btn_Guardar.setEnabled(false);
    }
    public void resetearGUI() {
        this.jt_Nombre.setText("");
        this.jt_Tiempo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_Puntuaciones = new javax.swing.JTable();
        jl_Nombre = new javax.swing.JLabel();
        jl_Tiempo = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Tiempo = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(520, 575));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jl_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/game over.gif"))); // NOI18N
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(30, 60, 441, 75);

        jtab_Puntuaciones.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jtab_Puntuaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtab_Puntuaciones.setEnabled(false);
        jScrollPane1.setViewportView(jtab_Puntuaciones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 320, 240, 90);

        jl_Nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Nombre.setForeground(new java.awt.Color(255, 255, 51));
        jl_Nombre.setText("Name: ");
        getContentPane().add(jl_Nombre);
        jl_Nombre.setBounds(150, 190, 85, 34);

        jl_Tiempo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Tiempo.setForeground(new java.awt.Color(255, 255, 51));
        jl_Tiempo.setText("Time:");
        getContentPane().add(jl_Tiempo);
        jl_Tiempo.setBounds(150, 250, 66, 34);

        jt_Nombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jt_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(240, 197, 100, 25);

        jt_Tiempo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jt_Tiempo.setEnabled(false);
        getContentPane().add(jt_Tiempo);
        jt_Tiempo.setBounds(240, 257, 100, 25);

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btn_Guardar.setActionCommand("Guardar");
        getContentPane().add(btn_Guardar);
        btn_Guardar.setBounds(370, 210, 45, 45);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, 0, 1549, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        resetearGUI();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FRM_JuegoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FRM_JuegoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FRM_JuegoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FRM_JuegoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FRM_JuegoTerminado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Tiempo;
    public javax.swing.JLabel jl_Titulo;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Tiempo;
    private javax.swing.JTable jtab_Puntuaciones;
    // End of variables declaration//GEN-END:variables
}
