/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_VentanaPrincipal;
import java.applet.AudioClip;
import modelo.HiloPrincipal;
import sun.applet.AppletAudioClip;

/**
 *
 * @author Carlos
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {
    
    HiloPrincipal hilo;
    Controlador_FRM_VentanaPrincipal controlador_FRM_VentanaPrincipal;
    AudioClip musicaFondo= new AppletAudioClip(getClass().getResource("/audio/musica.wav"));
    
    public FRM_VentanaPrincipal() {
        super("Start Window Bomber Fish");
        initComponents();
        setLocationRelativeTo(this);
        controlador_FRM_VentanaPrincipal= new Controlador_FRM_VentanaPrincipal(this);
        agregarEventos();
        hilo= new HiloPrincipal(this);
        hilo.start();
        reproducirMusica();
    }
    
    public void moverFondo() {
        if(jl_Fondo.getX()>-955) {
            this.jl_Fondo.setLocation(jl_Fondo.getX()-10, jl_Fondo.getY());
        }
        else {
            this.jl_Fondo.setLocation(0, jl_Fondo.getY());
        }
    }
    public void agregarEventos() {
        
        this.btn_Jugar.addActionListener(controlador_FRM_VentanaPrincipal);
        this.btn_Instrucciones.addActionListener(controlador_FRM_VentanaPrincipal);
        this.btn_Historia.addActionListener(controlador_FRM_VentanaPrincipal);
    }
    public void reproducirMusica() {
        musicaFondo.play();
        musicaFondo.loop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Personaje = new javax.swing.JLabel();
        btn_Jugar = new javax.swing.JButton();
        jl_Titulo = new javax.swing.JLabel();
        btn_Instrucciones = new javax.swing.JButton();
        btn_Historia = new javax.swing.JButton();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 580));
        getContentPane().setLayout(null);

        jl_Personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pez.gif"))); // NOI18N
        getContentPane().add(jl_Personaje);
        jl_Personaje.setBounds(230, 370, 90, 130);

        btn_Jugar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Jugar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_Jugar.setForeground(new java.awt.Color(255, 255, 51));
        btn_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.gif"))); // NOI18N
        btn_Jugar.setActionCommand("Jugar");
        btn_Jugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Jugar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btn_Jugar);
        btn_Jugar.setBounds(230, 260, 85, 30);

        jl_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titulo.gif"))); // NOI18N
        getContentPane().add(jl_Titulo);
        jl_Titulo.setBounds(80, 80, 440, 79);

        btn_Instrucciones.setBackground(new java.awt.Color(51, 51, 51));
        btn_Instrucciones.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_Instrucciones.setForeground(new java.awt.Color(255, 255, 51));
        btn_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/howtoplay.gif"))); // NOI18N
        btn_Instrucciones.setActionCommand("Instrucciones");
        btn_Instrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_Instrucciones);
        btn_Instrucciones.setBounds(390, 260, 164, 30);

        btn_Historia.setBackground(new java.awt.Color(51, 51, 51));
        btn_Historia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btn_Historia.setForeground(new java.awt.Color(255, 255, 51));
        btn_Historia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/score.gif"))); // NOI18N
        btn_Historia.setActionCommand("Puntuacion");
        btn_Historia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_Historia);
        btn_Historia.setBounds(30, 260, 106, 27);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(1, 0, 1549, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Historia;
    private javax.swing.JButton btn_Instrucciones;
    private javax.swing.JButton btn_Jugar;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Personaje;
    private javax.swing.JLabel jl_Titulo;
    // End of variables declaration//GEN-END:variables
}
